In [131]:
#agregación de datos
Datosagr=["Mi proyecto\Data\Broad.csv","Mi proyecto\Data\Frase.csv","Mi proyecto\Data\Kindle.csv","Mi proyecto\Data\Phase.csv"]

In [132]:
#Append de archivos con información a analizar
Muestra=[]
for archivos in Datosagr:
 df=pd.read_csv(archivos, sep=";")
 Muestra.append(df)

In [134]:
#Obtención de datos en un único data set, pre limpieza
datos_raw = pd.concat(Muestra, ignore_index=True)
datos_raw

,Estado,CAMPAIGN,Palabra clave,Tipo de coincidencia,Estado.1,Puja recomendada (bajo)(EUR),Puja recomendada (mediana)(EUR),Puja recomendada (alto)(EUR),Puja por palabra clave(EUR),PI del top de búsquedas,Impresiones,Clics,Tasa de clics (CTR),Inversión(EUR),Costo por clic (CPC)(EUR),Pedidos,Ventas(EUR),ACOS,KENP leídas,Estimación de regalías de KENP(EUR)
0,PAUSED,BROAD,victoria alvarez,BROAD,TARGETING_CLAUSE_PAUSED,0.15,0.18,0.31,0.10,NaN,98,0,0.0000,0.00,0.00,0,0.0,NaN,0,0.00
1,PAUSED,BROAD,trono de cristal saga,BROAD,TARGETING_CLAUSE_PAUSED,0.12,0.14,0.15,0.10,50.0%,1766,1,0.0006,0.09,0.09,0,0.0,NaN,0,0.00
2,PAUSED,BROAD,trono de cristal,BROAD,TARGETING_CLAUSE_PAUSED,0.13,0.14,0.20,0.10,NaN,7,0,0.0000,0.00,0.00,0,0.0,NaN,0,0.00
3,PAUSED,BROAD,top libros juveniles,BROAD,TARGETING_CLAUSE_PAUSED,0.14,0.14,0.16,0.10,NaN,5,0,0.0000,0.00,0.00,0,0.0,NaN,0,0.00
4,PAUSED,BROAD,tolkien aniversario,EXACT,TARGETING_CLAUSE_PAUSED,NaN,NaN,NaN,0.10,NaN,0,0,NaN,0.00,0.00,0,0.0,NaN,0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3425,ENABLED,PHASE,archivo de tormentas,PHRASE,CAMPAIGN_PAUSED,0.13,0.16,0.22,0.10,891891891891892%,1713,2,0.0012,0.96,0.48,0,0.0,NaN,646,2.66
3426,ENABLED,PHASE,amazon libros,PHRASE,CAMPAIGN_PAUSED,0.14,0.16,0.26,0.10,6153846153846150%,449,0,0.0000,0.00,0.00,0,0.0,NaN,0,0.00
3427,ENABLED,PHASE,14 años libros,PHRASE,CAMPAIGN_PAUSED,NaN,NaN,NaN,0.10,53333333333333300%,256,0,0.0000,0.00,0.00,0,0.0,NaN,0,0.00
3428,ENABLED,PHASE,12 años,PHRASE,CAMPAIGN_PAUSED,0.17,0.21,0.33,0.08,3514328808446450%,990,5,0.0051,3.92,0.78,0,0.0,NaN,0,0.00
3429,PAUSED,PHASE,10 años libros,PHRASE,CAMPAIGN_PAUSED,NaN,NaN,NaN,0.10,<5%,2,0,0.0000,0.00,0.00,0,0.0,NaN,0,0.00

In [135]:
#eliminar columnas on útiles estado  estado.1, pujas recomendadas, pl, acos, estimacion regalias, etc

datos_raw = datos_raw.drop(labels=["Estado", "Estado.1","Puja recomendada (bajo)(EUR)", "Puja recomendada (mediana)(EUR)","Puja recomendada (alto)(EUR)","PI del top de búsquedas", "Puja por palabra clave(EUR)", "Tasa de clics (CTR)", "ACOS", "KENP leídas","Estimación de regalías de KENP(EUR)","Ventas(EUR)"], axis=1)
datos_raw

,CAMPAIGN,Palabra clave,Tipo de coincidencia,Impresiones,Clics,Inversión(EUR),Costo por clic (CPC)(EUR),Pedidos
0,BROAD,victoria alvarez,BROAD,98,0,0.00,0.00,0
1,BROAD,trono de cristal saga,BROAD,1766,1,0.09,0.09,0
2,BROAD,trono de cristal,BROAD,7,0,0.00,0.00,0
3,BROAD,top libros juveniles,BROAD,5,0,0.00,0.00,0
4,BROAD,tolkien aniversario,EXACT,0,0,0.00,0.00,0
...,...,...,...,...,...,...,...,...
3425,PHASE,archivo de tormentas,PHRASE,1713,2,0.96,0.48,0
3426,PHASE,amazon libros,PHRASE,449,0,0.00,0.00,0
3427,PHASE,14 años libros,PHRASE,256,0,0.00,0.00,0
3428,PHASE,12 años,PHRASE,990,5,3.92,0.78,0
3429,PHASE,10 años libros,PHRASE,2,0,0.00,0.00,0

In [136]:
#simplificamos nombres de columnas complicadas

datos_raw= datos_raw.rename(columns={"Tipo de coincidencia": "concordancia", "Inversión(EUR)": "gasto", "Costo por clic (CPC)(EUR)": "CPC"})
datos_raw

,CAMPAIGN,Palabra clave,concordancia,Impresiones,Clics,gasto,CPC,Pedidos
0,BROAD,victoria alvarez,BROAD,98,0,0.00,0.00,0
1,BROAD,trono de cristal saga,BROAD,1766,1,0.09,0.09,0
2,BROAD,trono de cristal,BROAD,7,0,0.00,0.00,0
3,BROAD,top libros juveniles,BROAD,5,0,0.00,0.00,0
4,BROAD,tolkien aniversario,EXACT,0,0,0.00,0.00,0
...,...,...,...,...,...,...,...,...
3425,PHASE,archivo de tormentas,PHRASE,1713,2,0.96,0.48,0
3426,PHASE,amazon libros,PHRASE,449,0,0.00,0.00,0
3427,PHASE,14 años libros,PHRASE,256,0,0.00,0.00,0
3428,PHASE,12 años,PHRASE,990,5,3.92,0.78,0
3429,PHASE,10 años libros,PHRASE,2,0,0.00,0.00,0

In [137]:
#añadimos columnas con información interesante: rentabilidad
datos_raw["clicks para vta"] = round(datos_raw["Clics"]/datos_raw["Pedidos"], 1)

In [138]:
#añadimos columnas con información interesante: coste de venta
datos_raw["coste venta"]=round(datos_raw["gasto"]/datos_raw["Pedidos"],1)
datos_raw

,CAMPAIGN,Palabra clave,concordancia,Impresiones,Clics,gasto,CPC,Pedidos,clicks para vta,coste venta
0,BROAD,victoria alvarez,BROAD,98,0,0.00,0.00,0,NaN,NaN
1,BROAD,trono de cristal saga,BROAD,1766,1,0.09,0.09,0,inf,inf
2,BROAD,trono de cristal,BROAD,7,0,0.00,0.00,0,NaN,NaN
3,BROAD,top libros juveniles,BROAD,5,0,0.00,0.00,0,NaN,NaN
4,BROAD,tolkien aniversario,EXACT,0,0,0.00,0.00,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
3425,PHASE,archivo de tormentas,PHRASE,1713,2,0.96,0.48,0,inf,inf
3426,PHASE,amazon libros,PHRASE,449,0,0.00,0.00,0,NaN,NaN
3427,PHASE,14 años libros,PHRASE,256,0,0.00,0.00,0,NaN,NaN
3428,PHASE,12 años,PHRASE,990,5,3.92,0.78,0,inf,inf
3429,PHASE,10 años libros,PHRASE,2,0,0.00,0.00,0,NaN,NaN

In [139]:
#obtenemos tabla con datos únicamente con ventas para determinados analisis

datos_con_ventas = datos_raw[datos_raw["Pedidos"] > 0]
datos_con_ventas

,CAMPAIGN,Palabra clave,concordancia,Impresiones,Clics,gasto,CPC,Pedidos,clicks para vta,coste venta
85,BROAD,novelas juveniles 12 años,BROAD,161,4,2.44,0.61,1,4.0,2.4
94,BROAD,novelas de fantasia,BROAD,137,6,3.62,0.60,1,6.0,3.6
166,BROAD,literatura juvenil 16 años,BROAD,428,15,7.42,0.49,1,15.0,7.4
168,BROAD,literatura juvenil 12 años,BROAD,857,16,6.79,0.42,1,16.0,6.8
169,BROAD,literatura juvenil,BROAD,9223,57,31.80,0.56,3,19.0,10.6
...,...,...,...,...,...,...,...,...,...,...
3377,PHASE,laura gallego,EXACT,16433,47,20.58,0.44,1,47.0,20.6
3379,PHASE,las puertas de piedra,PHRASE,6105,9,1.03,0.11,2,4.5,0.5
3390,PHASE,juvenil,PHRASE,6724,43,31.91,0.74,3,14.3,10.6
3398,PHASE,harry potter libro,EXACT,8682,6,1.36,0.23,1,6.0,1.4
3424,PHASE,asesino de brujas,PHRASE,19504,22,2.63,0.12,1,22.0,2.6