In [130]:
import pandas as pd
import numpy as np

In [137]:
#rentabilidad
datos_raw["clicks para vta"] = round(datos_raw["Clics"]/datos_raw["Pedidos"], 1)

In [138]:
datos_raw["coste venta"]=round(datos_raw["gasto"]/datos_raw["Pedidos"],1)
datos_raw

,CAMPAIGN,Palabra clave,concordancia,Impresiones,Clics,gasto,CPC,Pedidos,clicks para vta,coste venta
0,BROAD,victoria alvarez,BROAD,98,0,0.00,0.00,0,NaN,NaN
1,BROAD,trono de cristal saga,BROAD,1766,1,0.09,0.09,0,inf,inf
2,BROAD,trono de cristal,BROAD,7,0,0.00,0.00,0,NaN,NaN
3,BROAD,top libros juveniles,BROAD,5,0,0.00,0.00,0,NaN,NaN
4,BROAD,tolkien aniversario,EXACT,0,0,0.00,0.00,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
3425,PHASE,archivo de tormentas,PHRASE,1713,2,0.96,0.48,0,inf,inf
3426,PHASE,amazon libros,PHRASE,449,0,0.00,0.00,0,NaN,NaN
3427,PHASE,14 años libros,PHRASE,256,0,0.00,0.00,0,NaN,NaN
3428,PHASE,12 años,PHRASE,990,5,3.92,0.78,0,inf,inf
3429,PHASE,10 años libros,PHRASE,2,0,0.00,0.00,0,NaN,NaN

In [139]:
datos_con_ventas = datos_raw[datos_raw["Pedidos"] > 0]
datos_con_ventas

,CAMPAIGN,Palabra clave,concordancia,Impresiones,Clics,gasto,CPC,Pedidos,clicks para vta,coste venta
85,BROAD,novelas juveniles 12 años,BROAD,161,4,2.44,0.61,1,4.0,2.4
94,BROAD,novelas de fantasia,BROAD,137,6,3.62,0.60,1,6.0,3.6
166,BROAD,literatura juvenil 16 años,BROAD,428,15,7.42,0.49,1,15.0,7.4
168,BROAD,literatura juvenil 12 años,BROAD,857,16,6.79,0.42,1,16.0,6.8
169,BROAD,literatura juvenil,BROAD,9223,57,31.80,0.56,3,19.0,10.6
...,...,...,...,...,...,...,...,...,...,...
3377,PHASE,laura gallego,EXACT,16433,47,20.58,0.44,1,47.0,20.6
3379,PHASE,las puertas de piedra,PHRASE,6105,9,1.03,0.11,2,4.5,0.5
3390,PHASE,juvenil,PHRASE,6724,43,31.91,0.74,3,14.3,10.6
3398,PHASE,harry potter libro,EXACT,8682,6,1.36,0.23,1,6.0,1.4
3424,PHASE,asesino de brujas,PHRASE,19504,22,2.63,0.12,1,22.0,2.6

In [140]:
#HIPOTESIS 1 CONCORDANCIAS

datos_concordancia = datos_con_ventas.groupby("concordancia").agg({"Pedidos": "sum", "CPC": "mean", "clicks para vta":"mean", "coste venta":"mean", "Impresiones":"sum","Clics":"sum"})
datos_concordancia = datos_concordancia.round(1)
datos_concordancia

              Pedidos  CPC  clicks para vta  coste venta  Impresiones  Clics
concordancia
BROAD             127  0.6              9.4          5.7       101102   1246
EXACT              65  0.5             20.1          9.8       366093   1368
PHRASE            116  0.5             14.8          7.0       548476   1833

In [141]:
#datos ventas

In [ ]:
#kw mas ineficientes

datos_sin_ventas = datos_raw[datos_raw["Pedidos"] == 0]
datos_ordenados = datos_sin_ventas.sort_values(by="gasto", ascending=False)
datos_ordenados

,CAMPAIGN,Palabra clave,concordancia,Impresiones,Clics,gasto,CPC,Pedidos,clicks para vta,coste venta
484,BROAD,libros fantasia,EXACT,4423,32,34.61,1.08,0,inf,inf
529,BROAD,libros de fantasía,BROAD,4071,33,29.08,0.88,0,inf,inf
717,BROAD,libros 14 años,BROAD,999,35,22.05,0.63,0,inf,inf
855,BROAD,libro 18 años,BROAD,2083,38,20.82,0.55,0,inf,inf
2419,Kindle,libros para kindle,BROAD,15613,61,20.43,0.33,0,inf,inf
...,...,...,...,...,...,...,...,...,...,...
1303,FRASE,libros brandon sanderson,PHRASE,0,0,0.00,0.00,0,NaN,NaN
1304,FRASE,libros baratos 12 años,PHRASE,0,0,0.00,0.00,0,NaN,NaN
1305,FRASE,libros aventuras niños 12 años,PHRASE,0,0,0.00,0.00,0,NaN,NaN
1306,FRASE,libros aventuras niños 10 años,PHRASE,0,0,0.00,0.00,0,NaN,NaN
3429,PHASE,10 años libros,PHRASE,2,0,0.00,0.00,0,NaN,NaN

In [ ]:
ordenado_impresiones=datos_raw.loc[con_impresiones].sort_values(by="Impresiones", ascending=False)
ordenado_impresiones

,CAMPAIGN,Palabra clave,concordancia,Impresiones,Clics,gasto,CPC,Pedidos,clicks para vta,coste venta,ratio impresion click
23,BROAD,o principe cruel,BROAD,111703,105,19.05,0.18,0,inf,inf,0.0
2566,PHASE,trono de cristal,EXACT,91182,74,14.50,0.20,1,74.0,14.5,0.0
3408,PHASE,el trono de cristal,PHRASE,85111,83,16.04,0.19,0,inf,inf,0.0
1507,FRASE,el trono de cristal,PHRASE,81935,59,11.53,0.20,2,29.5,5.8,0.0
1195,FRASE,libros juvenil,PHRASE,64034,67,22.07,0.33,1,67.0,22.1,0.0
...,...,...,...,...,...,...,...,...,...,...,...
2648,PHASE,novelas juveniles 12 años,PHRASE,102,1,1.18,1.18,0,inf,inf,1.0
2361,Kindle,libros para 13 años de chicas,BROAD,102,0,0.00,0.00,0,NaN,NaN,0.0
1684,Kindle,libros juvenil 12 años,PHRASE,101,5,2.51,0.50,1,5.0,2.5,5.0
2633,PHASE,novelas medievales,PHRASE,101,0,0.00,0.00,0,NaN,NaN,0.0
3016,PHASE,libros fantasy,PHRASE,101,1,0.42,0.42,0,inf,inf,1.0

In [ ]:
#ventas con mayor coste 


ventas_coste_alto= datos_con_ventas.sort_values(by="coste venta", ascending=False)
ventas_coste_alto.head(10)

,CAMPAIGN,Palabra clave,concordancia,Impresiones,Clics,gasto,CPC,Pedidos,clicks para vta,coste venta
885,BROAD,laura gallego,EXACT,8429,61,51.62,0.85,1,61.0,51.6
3296,PHASE,libro fantasia,PHRASE,1890,60,31.93,0.53,1,60.0,31.9
2981,PHASE,libros juveniles,PHRASE,56084,168,115.86,0.69,4,42.0,29.0
569,BROAD,libros de adolescentes,EXACT,9369,133,95.43,0.72,4,33.2,23.9
1195,FRASE,libros juvenil,PHRASE,64034,67,22.07,0.33,1,67.0,22.1
774,BROAD,libro juveniles,EXACT,40044,251,129.97,0.52,6,41.8,21.7
3377,PHASE,laura gallego,EXACT,16433,47,20.58,0.44,1,47.0,20.6
837,BROAD,libro adolescentes,PHRASE,3024,21,19.19,0.91,1,21.0,19.2
288,BROAD,libros para 13 años,PHRASE,2458,70,38.44,0.55,2,35.0,19.2
537,BROAD,libros de fantasia juveniles,EXACT,3256,47,18.96,0.40,1,47.0,19.0

In [ ]:
#mayor cpc

rdos=datos_con_ventas.sort_values(by="Pedidos", ascending=False)
rdos.head(25)

,CAMPAIGN,Palabra clave,concordancia,Impresiones,Clics,gasto,CPC,Pedidos,clicks para vta,coste venta
436,BROAD,libros juvenil,PHRASE,52771,284,144.41,0.51,13,21.8,11.1
838,BROAD,libro adolescentes,EXACT,7321,100,94.67,0.95,10,10.0,9.5
274,BROAD,libros para adolescentes,BROAD,18477,168,96.23,0.57,10,16.8,9.6
1319,FRASE,libros adolescentes,PHRASE,23846,71,48.60,0.68,7,10.1,6.9
647,BROAD,libros adolescentes 14 años,BROAD,3930,80,58.02,0.73,7,11.4,8.3
308,BROAD,libros niños 12 años mas vendidos,BROAD,3577,49,40.83,0.83,7,7.0,5.8
268,BROAD,libros para adolescentes de 13 años,BROAD,2982,57,58.23,1.02,7,8.1,8.3
434,BROAD,libros juveniles,EXACT,59705,178,99.28,0.56,7,25.4,14.2
774,BROAD,libro juveniles,EXACT,40044,251,129.97,0.52,6,41.8,21.7
285,BROAD,libros para 14 años,PHRASE,1592,53,38.55,0.73,5,10.6,7.7
863,BROAD,libro 15 años,BROAD,2074,40,26.89,0.67,5,8.0,5.4
654,BROAD,libros adolescentes,EXACT,9018,76,42.74,0.56,5,15.2,8.5
420,BROAD,libros juveniles 14 años,BROAD,4880,71,44.54,0.63,4,17.8,11.1
2981,PHASE,libros juveniles,PHRASE,56084,168,115.86,0.69,4,42.0,29.0
773,BROAD,libro juveniles,BROAD,11465,68,42.87,0.63,4,17.0,10.7
569,BROAD,libros de adolescentes,EXACT,9369,133,95.43,0.72,4,33.2,23.9
263,BROAD,libros para adolescentes de 16 años,PHRASE,2859,58,31.16,0.54,4,14.5,7.8
857,BROAD,libro 17 años,BROAD,744,19,9.01,0.47,4,4.8,2.3
211,BROAD,libros para niños de 14 años,BROAD,690,17,15.37,0.90,4,4.2,3.8
865,BROAD,libro 14 años mas vendido,BROAD,1031,26,15.21,0.59,4,6.5,3.8
1080,FRASE,libros para kindle,PHRASE,14989,75,48.79,0.65,4,18.8,12.2
868,BROAD,libro 13 años mas vendido,BROAD,1080,35,22.66,0.65,4,8.8,5.7
427,BROAD,libros juveniles 12 años,PHRASE,3420,48,29.81,0.62,4,12.0,7.5
2765,PHASE,libros para niños de 12 años,EXACT,19616,85,23.82,0.28,3,28.3,7.9
802,BROAD,libro espada,BROAD,1113,5,2.84,0.57,3,1.7,0.9

In [ ]:
datos_raw.size

37730

In [ ]:
#correlacion spearman
datos_con_ventas.corr(method="spearman")

,Impresiones,Clics,gasto,CPC,Pedidos,clicks para vta,coste venta,ratio impresion click
Impresiones,1.000000,0.762149,0.626726,-0.064953,0.405168,0.723582,0.584054,-0.736932
Clics,0.762149,1.000000,0.934414,0.143529,0.642582,0.875645,0.839365,-0.210238
gasto,0.626726,0.934414,1.000000,0.453798,0.656525,0.782819,0.903561,-0.091406
CPC,-0.064953,0.143529,0.453798,1.000000,0.271127,0.005618,0.402040,0.182004
Pedidos,0.405168,0.642582,0.656525,0.271127,1.000000,0.225179,0.296281,-0.020051
clicks para vta,0.723582,0.875645,0.782819,0.005618,0.225179,1.000000,0.892685,-0.261352
coste venta,0.584054,0.839365,0.903561,0.402040,0.296281,0.892685,1.000000,-0.116700
ratio impresion click,-0.736932,-0.210238,-0.091406,0.182004,-0.020051,-0.261352,-0.116700,1.000000

In [ ]:
datos_concordancia.corr(method="spearman")

,Pedidos,CPC,clicks para vta,coste venta,Impresiones,Clics
Pedidos,1.000000,0.866025,-1.000000,-1.000000,-0.500000,-0.500000
CPC,0.866025,1.000000,-0.866025,-0.866025,-0.866025,-0.866025
clicks para vta,-1.000000,-0.866025,1.000000,1.000000,0.500000,0.500000
coste venta,-1.000000,-0.866025,1.000000,1.000000,0.500000,0.500000
Impresiones,-0.500000,-0.866025,0.500000,0.500000,1.000000,1.000000
Clics,-0.500000,-0.866025,0.500000,0.500000,1.000000,1.000000

In [ ]:
from scipy import stats
from scipy import interpolate

In [ ]:
#correlacion gasto con pedidos
feature_name = 'gasto'
target_column = 'Pedidos'

In [ ]:
#correlacion clics con pedidos
feature_name = 'Clics'
target_column = 'Pedidos'

In [ ]:
#cuadrante media y comparar que tengan pedidos si

In [ ]:
from scipy import stats
import statsmodels.api as sm

In [ ]:
from statsmodels.formula.api import ols

In [163]:
#Predecir pedidos según clics

formula = 'Pedidos ~ Clics'
lm = ols(formula, datos_raw).fit()
print(lm.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                Pedidos   R-squared:                       0.623
Model:                            OLS   Adj. R-squared:                  0.623
Method:                 Least Squares   F-statistic:                     5664.
Date:                Sat, 15 Apr 2023   Prob (F-statistic):               0.00
Time:                        17:09:14   Log-Likelihood:                -1341.2
No. Observations:                3430   AIC:                             2686.
Df Residuals:                    3428   BIC:                             2699.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.0052      0.006      0.835      0.404      -0.007       0.017
Clics          0.0406      0.001     75.260      0.000       0.040       0.042
==============================================================================
Omnibus:                     3318.993   Durbin-Watson:                   1.894
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           968149.457
Skew:                           3.981   Prob(JB):                         0.00
Kurtosis:                      84.920   Cond. No.                         11.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [164]:
#Predecir pedidos según gasto

formula = 'Pedidos ~ gasto'
lm = ols(formula, datos_raw).fit()
print(lm.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                Pedidos   R-squared:                       0.706
Model:                            OLS   Adj. R-squared:                  0.706
Method:                 Least Squares   F-statistic:                     8251.
Date:                Sat, 15 Apr 2023   Prob (F-statistic):               0.00
Time:                        17:10:08   Log-Likelihood:                -911.76
No. Observations:                3430   AIC:                             1828.
Df Residuals:                    3428   BIC:                             1840.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.0111      0.005      2.032      0.042       0.000       0.022
gasto          0.0765      0.001     90.836      0.000       0.075       0.078
==============================================================================
Omnibus:                     1920.159   Durbin-Watson:                   1.901
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           614438.697
Skew:                           1.435   Prob(JB):                         0.00
Kurtosis:                      68.506   Cond. No.                         6.57
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [166]:
#regresion multiple

formula = 'Pedidos ~ gasto + Clics '
lm = ols(formula, datos_raw).fit()
print(lm.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                Pedidos   R-squared:                       0.707
Model:                            OLS   Adj. R-squared:                  0.707
Method:                 Least Squares   F-statistic:                     4137.
Date:                Sat, 15 Apr 2023   Prob (F-statistic):               0.00
Time:                        17:11:01   Log-Likelihood:                -907.94
No. Observations:                3430   AIC:                             1822.
Df Residuals:                    3427   BIC:                             1840.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.0126      0.005      2.295      0.022       0.002       0.023
gasto          0.0835      0.003     31.385      0.000       0.078       0.089
Clics         -0.0042      0.002     -2.766      0.006      -0.007      -0.001
==============================================================================
Omnibus:                     1839.995   Durbin-Watson:                   1.900
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           627948.606
Skew:                           1.301   Prob(JB):                         0.00
Kurtosis:                      69.235   Cond. No.                         13.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:
#KEYWORDS

In [ ]:
#Media CPC
datos_con_ventas[["CPC", "Clics", "coste venta", "Pedidos", "clicks para vta"]].mean()

CPC                 0.540728
Clics              29.450331
coste venta         7.060265
Pedidos             2.039735
clicks para vta    13.696689
dtype: float64

In [ ]:
datos_con_ventas["% imp clic"]=datos_con_ventas["Clics"]/datos_con_ventas["Impresiones"]

c:\Users\Abraham\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
#agrupo kw por palabra clave 

kw_exitosas=datos_con_ventas.groupby("Palabra clave").agg({"Pedidos": "sum", "CPC": "mean", "clicks para vta":"mean", "coste venta":"mean", "Impresiones":"sum","Clics":"sum", "% imp clic":"mean"})
kw_exitosas

TypeError: '>' not supported between instances of 'str' and 'int'

In [ ]:
CPC                 0.540728
Clics              29.450331
coste venta         7.060265
Pedidos             2.039735
clicks para vta    13.696689
dtype: float64

In [ ]:
kw_exitosas.query('Pedidos > 2 and `coste venta` < 7.06 and `clicks para vta` < 13.69 and CPC < 0.55')

,Pedidos,CPC,clicks para vta,coste venta,Impresiones,Clics,% imp clic
Palabra clave,,,,,,,
la erupcion zafiro,3,0.080,5.00,0.45,154,16,0.241667
las puertas de piedra,3,0.180,12.25,2.75,19295,29,0.001495
libro 17 años,4,0.470,4.80,2.30,744,19,0.025538
libros 16 años,4,0.465,2.65,1.60,520,14,0.137597
libros de fantasia adultos,4,0.515,6.50,3.30,1187,26,0.022445
libros juveniles 12 años,6,0.490,12.00,5.90,5916,72,0.015603
libros kindle,4,0.540,11.50,5.45,12444,61,0.004213

In [ ]:
#sin agrupar por palabra clave y teniendo en cuenta concordancia
datos_con_ventas.query('Pedidos > 1 and `coste venta` < 8 and `clicks para vta` < 15 and CPC < 0.65')

,CAMPAIGN,Palabra clave,concordancia,Impresiones,Clics,gasto,CPC,Pedidos,clicks para vta,coste venta,ratio imp clic,% imp clic
263,BROAD,libros para adolescentes de 16 años,PHRASE,2859,58,31.16,0.54,4,14.5,7.8,49.293103,0.020287
353,BROAD,libros mas vendidos de 12 años,BROAD,473,11,4.42,0.40,2,5.5,2.2,43.000000,0.023256
423,BROAD,libros juveniles 13 años,BROAD,1128,20,12.25,0.61,2,10.0,6.1,56.400000,0.017730
427,BROAD,libros juveniles 12 años,PHRASE,3420,48,29.81,0.62,4,12.0,7.5,71.250000,0.014035
541,BROAD,libros de fantasia adultos,BROAD,666,12,6.94,0.58,2,6.0,3.5,55.500000,0.018018
802,BROAD,libro espada,BROAD,1113,5,2.84,0.57,3,1.7,0.9,222.600000,0.004492
857,BROAD,libro 17 años,BROAD,744,19,9.01,0.47,4,4.8,2.3,39.157895,0.025538
860,BROAD,libro 15 años mas vendido,BROAD,331,8,3.49,0.44,2,4.0,1.7,41.375000,0.024169
865,BROAD,libro 14 años mas vendido,BROAD,1031,26,15.21,0.59,4,6.5,3.8,39.653846,0.025218
893,BROAD,la erupcion zafiro,BROAD,144,12,1.56,0.13,2,6.0,0.8,12.000000,0.083333
1267,FRASE,libros de fantasia adultos,PHRASE,521,14,6.26,0.45,2,7.0,3.1,37.214286,0.026871
1275,FRASE,libros de aventuras para adultos,PHRASE,128,3,1.87,0.62,2,1.5,0.9,42.666667,0.023438
1434,FRASE,laura gallego,PHRASE,21031,40,11.69,0.29,3,13.3,3.9,525.775000,0.001902
2725,PHASE,literatura juvenil,PHRASE,1353,18,9.88,0.55,2,9.0,4.9,75.166667,0.013304
2972,PHASE,libros juveniles 13 años,PHRASE,638,11,5.63,0.51,2,5.5,2.8,58.000000,0.017241
3159,PHASE,libros adolescentes,PHRASE,11318,15,1.39,0.09,2,7.5,0.7,754.533333,0.001325
3379,PHASE,las puertas de piedra,PHRASE,6105,9,1.03,0.11,2,4.5,0.5,678.333333,0.001474

In [ ]:
#Ordeno kw en funcion de mayor número de ventas

kw_exitosas=kw_exitosas.sort_values(by="coste venta", ascending=True)
kw_exitosas.head(25)

,Pedidos,CPC,clicks para vta,coste venta,Impresiones,Clics
Palabra clave,,,,,,
laura gallego finis mundi,1,0.230,1.00,0.20,131,1
libro fantasia 18 años,1,0.250,1.00,0.20,7,1
libro fantasia 12 años,1,0.250,1.00,0.20,11,1
libros de niños de 10 años,1,0.110,3.00,0.30,346,3
libros niños 10 años,1,0.140,2.00,0.30,184,2
la erupcion zafiro,3,0.080,5.00,0.45,154,16
libros de lectura para 12 años,1,0.510,1.00,0.50,51,1
libros para niños 18 años,1,0.610,1.00,0.60,9,1
libros 11 años niño,1,0.670,1.00,0.70,1,1
libros 11 años aventuras,1,0.240,3.00,0.70,13,3
libros 10-12 años,1,0.360,2.00,0.70,33,2
trono de cristal saga,1,0.340,2.00,0.70,1153,2
libros juveniles 15 años,1,0.420,2.00,0.80,160,2
libros mas vendidos adolescentes,1,0.190,4.00,0.80,1254,4
libro espada,3,0.570,1.70,0.90,1113,5
saga trono de cristal,1,0.130,7.00,0.90,11709,7
libros de aventuras para adultos,2,0.620,1.50,0.90,128,3
novelas juveniles,1,0.480,2.00,1.00,1123,2
libros adolescentes 14 anos,1,0.210,5.00,1.00,2610,5
libros 18 años mas vendidos,1,0.480,2.00,1.00,12,2
libros 22 años,1,0.390,3.00,1.20,50,3
novela juvenil 16 años,1,0.690,2.00,1.40,22,2
harry potter libro,1,0.230,6.00,1.40,8682,6
juegos del hambre libro,1,0.700,2.00,1.40,2306,2
libros 16 años,4,0.465,2.65,1.60,520,14

0.540728476821192